CREATE VIEW VIEW_USER_INFORMATION AS
SELECT U.USER_ID, U.FIRST_NAME, U.LAST_NAME, 
    U.YEAR_OF_BIRTH, U.MONTH_OF_BIRTH, U.DAY_OF_BIRTH, 
    U.GENDER, C1.CITY_NAME city1, C1.STATE_NAME state1, 
    C1.COUNTRY_NAME country1, C2.CITY_NAME city2, 
    C2.STATE_NAME state2, C2.COUNTRY_NAME country2, 
    P.INSTITUTION, E.PROGRAM_YEAR, P.CONCENTRATION, 
    P.DEGREE
FROM USERS U
LEFT JOIN USER_CURRENT_CITIES CC
    ON CC.USER_ID = U.USER_ID
LEFT JOIN CITIES C1
    ON CC.CURRENT_CITY_ID = C1.CITY_ID
LEFT JOIN USER_HOMETOWN_CITIES HC
    ON HC.USER_ID = U.USER_ID
LEFT JOIN CITIES C2
    ON HC.HOMETOWN_CITY_ID = C2.CITY_ID
LEFT JOIN EDUCATION E
    ON U.USER_ID = E.USER_ID
LEFT JOIN PROGRAMS P
    ON E.PROGRAM_ID = P.PROGRAM_ID
;

CREATE VIEW VIEW_ARE_FRIENDS AS
SELECT F.USER1_ID, F.USER2_ID
FROM FRIENDS F;

CREATE VIEW VIEW_PHOTO_INFORMATION AS
SELECT P.ALBUM_ID, A.ALBUM_OWNER_ID, A.COVER_PHOTO_ID, A.ALBUM_NAME, 
A.ALBUM_CREATED_TIME, A.ALBUM_MODIFIED_TIME, A.ALBUM_LINK, A.ALBUM_VISIBILITY, 
P.PHOTO_ID, P.PHOTO_CAPTION, P.PHOTO_CREATED_TIME, P.PHOTO_MODIFIED_TIME, 
P.PHOTO_LINK
FROM ALBUMS A, PHOTOS P
WHERE P.ALBUM_ID = A.ALBUM_ID;

CREATE VIEW VIEW_EVENT_INFORMATION AS
SELECT U.EVENT_ID, U.EVENT_CREATOR_ID, U.EVENT_NAME, U.EVENT_TAGLINE, 
U.EVENT_DESCRIPTION, U.EVENT_HOST, U.EVENT_TYPE, U.EVENT_SUBTYPE, 
U.EVENT_ADDRESS, C.CITY_NAME, C.STATE_NAME, C.COUNTRY_NAME, 
U.EVENT_START_TIME, U.EVENT_END_TIME
FROM USER_EVENTS U, CITIES C
WHERE U.EVENT_CITY_ID = C.CITY_ID;

CREATE VIEW VIEW_TAG_INFORMATION AS
SELECT T.TAG_PHOTO_ID, T.TAG_SUBJECT_ID, T.TAG_CREATED_TIME, T.TAG_X, 
T.TAG_Y
FROM TAGS T;