DROP TRIGGER order_friends_pairs;

DROP TABLE FRIENDS;

DROP TABLE USER_CURRENT_CITIES;

DROP TABLE USER_HOMETOWN_CITIES;

DROP TABLE MESSAGES;

ALTER TABLE EDUCATION
DROP CONSTRAINT year;
DROP TABLE EDUCATION;

ALTER TABLE PROGRAMS
DROP CONSTRAINT degreeStuff;
DROP TABLE PROGRAMS;

DROP TABLE PARTICIPANTS;

DROP TABLE USER_EVENTS;

DROP TABLE TAGS;

ALTER TABLE ALBUMS
DROP CONSTRAINT photAlbum;

ALTER TABLE PHOTOS
DROP CONSTRAINT albPhoto;

DROP TABLE PHOTOS;

DROP TABLE ALBUMS;

ALTER TABLE CITIES
DROP CONSTRAINT loc;
DROP TABLE CITIES;

DROP TABLE USERS;